# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [34]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
# Import API key
from config import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [35]:
df=pd.read_csv("../WeatherPy/cities.csv")
df.head()

,Unnamed: 0,City,Latitude,Longtitude,Temp,Max Temp,Cloudiness,Humidity,Wind
0,0,luanda,-8.84,13.23,84.20,84.20,75.0,74.0,13.87
1,1,leiyang,26.40,112.86,49.14,49.14,95.0,90.0,3.76
2,2,yellowknife,62.46,-114.35,-2.74,-2.20,75.0,77.0,16.11
3,3,hermanus,-34.42,19.23,67.80,70.00,49.0,80.0,5.99
4,4,kharan,28.58,65.42,54.64,54.64,0.0,47.0,8.43

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [36]:
#configure gmaps with API key
gmaps.configure(api_key=g_key)

In [65]:
#Store lat and long into Locations
#df=df.dropna()
locations=df[['Latitude','Longtitude']].astype(float)


humid=df['Humidity'].astype(float)

In [66]:
#fig=gmaps.figure()
figure_layout = {
    'width': '1600px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
heat_layer=gmaps.heatmap_layer(locations,weights=humid,dissipating=False,max_intensity=100,point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [67]:
df_narrow=df[(df['Max Temp']<70) & (df['Wind']<10) & (df['Cloudiness']==0)]
df_narrow

,Unnamed: 0,City,Latitude,Longtitude,Temp,Max Temp,Cloudiness,Humidity,Wind
4,4,kharan,28.58,65.42,54.64,54.64,0.0,47.0,8.43
10,10,darhan,49.49,105.92,-9.49,-9.49,0.0,88.0,2.04
23,23,ranong,28.02,73.30,58.59,58.59,0.0,46.0,7.76
102,102,airai,59.70,150.17,-10.46,-10.46,0.0,83.0,5.53
106,106,cherskiy,29.03,21.55,53.82,53.82,0.0,55.0,5.73
111,111,hasaki,30.92,66.45,36.99,36.99,0.0,60.0,1.36
138,138,mar del plata,32.25,67.25,13.95,13.95,0.0,75.0,2.68
190,190,belushya guba,63.83,20.26,29.79,30.20,0.0,80.0,4.70
200,200,ust-nera,64.38,-173.30,-12.89,-12.89,0.0,88.0,2.51
206,206,tucuman,71.92,114.08,-39.96,-39.96,0.0,93.0,7.96
220,220,iqaluit,17.47,-97.23,68.29,68.29,0.0,39.0,4.43
286,286,port lincoln,30.44,48.17,52.79,53.60,0.0,62.0,4.70
291,291,danjiangkou,25.52,90.22,55.80,55.80,0.0,53.0,2.53
294,294,rapid valley,45.67,18.98,29.43,32.00,0.0,92.0,6.93
307,307,slidell,45.76,106.27,1.38,1.38,0.0,75.0,8.48
310,310,belmopan,25.02,37.27,55.49,55.49,0.0,37.0,9.95
396,396,abilene,54.43,113.60,-21.14,-21.14,0.0,78.0,5.26
402,402,mullaitivu,-28.55,16.43,68.32,68.32,0.0,76.0,8.37
466,466,lyuban,59.38,143.30,-22.68,-22.68,0.0,69.0,7.02
518,518,santarem,22.93,57.53,61.56,61.56,0.0,60.0,6.22
519,519,narasannapeta,57.26,16.45,34.99,37.00,0.0,64.0,5.82
546,546,mitsamiouli,56.66,16.36,35.35,37.00,0.0,64.0,5.82

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [68]:
hotel_df=df_narrow[['City','Latitude','Longtitude','Humidity']]
#hotel_df['Location']=list(zip(hotel_df.Latitude,hotel_df.Longtitude))
#hotel_df['Location'].str.replace(r"\(.*\)","")
#Location=f"{Latitude},{Longtitude}"
hotel_df

              City  Latitude  Longtitude  Humidity
4           kharan     28.58       65.42      47.0
10          darhan     49.49      105.92      88.0
23          ranong     28.02       73.30      46.0
102          airai     59.70      150.17      83.0
106       cherskiy     29.03       21.55      55.0
111         hasaki     30.92       66.45      60.0
138  mar del plata     32.25       67.25      75.0
190  belushya guba     63.83       20.26      80.0
200       ust-nera     64.38     -173.30      88.0
206        tucuman     71.92      114.08      93.0
220        iqaluit     17.47      -97.23      39.0
286   port lincoln     30.44       48.17      62.0
291    danjiangkou     25.52       90.22      53.0
294   rapid valley     45.67       18.98      92.0
307        slidell     45.76      106.27      75.0
310       belmopan     25.02       37.27      37.0
396        abilene     54.43      113.60      78.0
402     mullaitivu    -28.55       16.43      76.0
466         lyuban     59.38      143.30      69.0
518       santarem     22.93       57.53      60.0
519  narasannapeta     57.26       16.45      64.0
546    mitsamiouli     56.66       16.36      64.0

In [69]:
hotel_df.loc[0:,'name'] = ""
hotel_df.loc[0:,'location']=hotel_df['Latitude'].astype(str)+','+hotel_df['Longtitude'].astype(str)
#hotel_df['address'] = ""
#types_df['price_level'] = ""
#types_df['rating'] = ""
hotel_df

              City  Latitude  Longtitude  Humidity name      location
4           kharan     28.58       65.42      47.0        28.58,65.42
10          darhan     49.49      105.92      88.0       49.49,105.92
23          ranong     28.02       73.30      46.0         28.02,73.3
102          airai     59.70      150.17      83.0        59.7,150.17
106       cherskiy     29.03       21.55      55.0        29.03,21.55
111         hasaki     30.92       66.45      60.0        30.92,66.45
138  mar del plata     32.25       67.25      75.0        32.25,67.25
190  belushya guba     63.83       20.26      80.0        63.83,20.26
200       ust-nera     64.38     -173.30      88.0       64.38,-173.3
206        tucuman     71.92      114.08      93.0       71.92,114.08
220        iqaluit     17.47      -97.23      39.0       17.47,-97.23
286   port lincoln     30.44       48.17      62.0        30.44,48.17
291    danjiangkou     25.52       90.22      53.0        25.52,90.22
294   rapid valley     45.67       18.98      92.0        45.67,18.98
307        slidell     45.76      106.27      75.0       45.76,106.27
310       belmopan     25.02       37.27      37.0        25.02,37.27
396        abilene     54.43      113.60      78.0        54.43,113.6
402     mullaitivu    -28.55       16.43      76.0       -28.55,16.43
466         lyuban     59.38      143.30      69.0        59.38,143.3
518       santarem     22.93       57.53      60.0        22.93,57.53
519  narasannapeta     57.26       16.45      64.0        57.26,16.45
546    mitsamiouli     56.66       16.36      64.0        56.66,16.36

In [70]:

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "rankby":"distance",
    "type": "lodging",
    "key": g_key
}
# use iterrows to iterate through pandas dataframe
for index,row in hotel_df.iterrows():

    # get coordinates type from df!!!!
    city_name = row['City']
    hotel_loc = row['location']
   
    # add location to params dict
    params['location'] =hotel_loc
    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: { hotel_loc}.")
    response = requests.get(base_url, params=params).json()
    # extract results
    results = response['results']
    #print({results})
    try:
        #print(f"Closest hotel in {city_name}  is {results[0]['name']}.")
        
        hotel_df.loc[index,'name'] = results[0]['name']
        #types_df.loc[index, 'address'] = results[0]['vicinity']
        #types_df.loc[index, 'price_level'] = results[0]['price_level']
        #types_df.loc[index, 'rating'] = results[0]['rating']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Retrieving Results for Index 4: 28.58,65.42.
Retrieving Results for Index 10: 49.49,105.92.
Retrieving Results for Index 23: 28.02,73.3.
Retrieving Results for Index 102: 59.7,150.17.
Missing field/result... skipping.
Retrieving Results for Index 106: 29.03,21.55.
Retrieving Results for Index 111: 30.92,66.45.
Retrieving Results for Index 138: 32.25,67.25.
Missing field/result... skipping.
Retrieving Results for Index 190: 63.83,20.26.
Retrieving Results for Index 200: 64.38,-173.3.
Missing field/result... skipping.
Retrieving Results for Index 206: 71.92,114.08.
Retrieving Results for Index 220: 17.47,-97.23.
Retrieving Results for Index 286: 30.44,48.17.
Retrieving Results for Index 291: 25.52,90.22.
Retrieving Results for Index 294: 45.67,18.98.
Retrieving Results for Index 307: 45.76,106.27.
Retrieving Results for Index 310: 25.02,37.27.
Retrieving Results for Index 396: 54.43,113.6.
Missing field/result... skipping.
Retrieving Results for Index 402: -28.55,16.43.
Retrieving Results for Index 466: 59.38,143.3.
Retrieving Results for Index 518: 22.93,57.53.
Retrieving Results for Index 519: 57.26,16.45.
Retrieving Results for Index 546: 56.66,16.36.

In [71]:
hotel_df

,City,Latitude,Longtitude,Humidity,name,location
4,kharan,28.58,65.42,47.0,Ghani Hasrat House,"28.58,65.42"
10,darhan,49.49,105.92,88.0,өнгөт хороолол,"49.49,105.92"
23,ranong,28.02,73.30,46.0,Rukhminesh nd Krishna Mani Mention,"28.02,73.3"
102,airai,59.70,150.17,83.0,,"59.7,150.17"
106,cherskiy,29.03,21.55,55.0,Jalu Hotel,"29.03,21.55"
111,hasaki,30.92,66.45,60.0,Niamatt parda Center,"30.92,66.45"
138,mar del plata,32.25,67.25,75.0,,"32.25,67.25"
190,belushya guba,63.83,20.26,80.0,First Hotel Dragonen,"63.83,20.26"
200,ust-nera,64.38,-173.30,88.0,,"64.38,-173.3"
206,tucuman,71.92,114.08,93.0,Saskylakh Aeroport,"71.92,114.08"
220,iqaluit,17.47,-97.23,39.0,Hotel Santillan,"17.47,-97.23"
286,port lincoln,30.44,48.17,62.0,مامور سرا مخابرات و مایکروویو,"30.44,48.17"
291,danjiangkou,25.52,90.22,53.0,ABC Girls' Hostel,"25.52,90.22"
294,rapid valley,45.67,18.98,92.0,ART Hostel,"45.67,18.98"
307,slidell,45.76,106.27,75.0,Ганбат.В,"45.76,106.27"
310,belmopan,25.02,37.27,37.0,عبدالله ظافر الثوعي,"25.02,37.27"
396,abilene,54.43,113.60,78.0,,"54.43,113.6"
402,mullaitivu,-28.55,16.43,76.0,Sperrgebiet Guest House,"-28.55,16.43"
466,lyuban,59.38,143.30,69.0,Prozhivaniye V Okhotske,"59.38,143.3"
518,santarem,22.93,57.53,60.0,مؤسسة الهلال الأبيض للخدمات العقاريه و مقاولات,"22.93,57.53"
519,narasannapeta,57.26,16.45,64.0,STF Vandrarhem Oscar,"57.26,16.45"
546,mitsamiouli,56.66,16.36,64.0,Wohnmobilstellplatz Ölandskajen,"56.66,16.36"

In [54]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{City}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longtitude"]]

In [55]:
# Add marker layer ontop of heat map


# Display Map

In [63]:
#coord=hotel_df['location']
#lat=hotel_df['']
#coord
figure_layout = {
    'width': '1600px',
    'height': '800px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)
heat_layer=gmaps.heatmap_layer(locations,weights=humid,dissipating=False,max_intensity=100,point_radius=1)
markers=gmaps.marker_layer(hotel_df[['Latitude','Longtitude']])
fig.add_layer(heat_layer)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='800px', margin='0 auto 0 auto', padding='1px', wi…

In [ ]:
print(coord)